name: build

on:
  repository_dispatch:
    types: [build]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to dockerhub
      run: |
        docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Setup Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Checkout Zwave2Mqtt-Docker
      uses: actions/checkout@v2
    - name: Cross arch build
      run: |
        sudo apt-get install wget
        cd bin
        chmod +x buildx.sh
        ./buildx.sh
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled