name: build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to dockerhub and enable experimental features
      run: |
        docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Setup Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Checkout Zwave2Mqtt-Docker
      uses: actions/checkout@v2
    - name: Cross arch build
      run: |
        sudo apt-get install wget
        cd bin
        ./get_qemu.sh
        ./build.sh